# Generated by Django 5.1.7 on 2025-04-07 13:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Osobní vozidlo', 'Passenger Vehicle'), ('Nákladní vozidlo', 'Truck')], default='Osobní vozidlo', max_length=50)),
                ('plate_number', models.CharField(max_length=15)),
                ('fuel_type', models.CharField(choices=[('Nafta', 'Diesel'), ('Benzín', 'Gasoline'), ('Elektrický pohon', 'Electric'), ('LPG', 'Lpg')], default='Elektrický pohon', max_length=20)),
                ('technical_inspection_date', models.DateField()),
                ('highway_ticket_validity', models.DateField()),
                ('is_usable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Hlavní pracovní poměr', 'Main Employment Relationship'), ('Dohoda o pracovní činnosti', 'Work Agreement'), ('Dohoda o provedení práce', 'Performance Work Agreement'), ('Částečný pracovní úvazek', 'Part Time Job')], default='Hlavní pracovní poměr', max_length=32)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InternalDirectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('effective_date', models.DateField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.IntegerField(default=8)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonalCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('valid_until', models.DateField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RealEstates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Budova', 'Building'), ('Nájemní byt', 'Rental Apartment'), ('Společenská místnost', 'Social Hall'), ('Zasedací místnost', 'Conference Room')], default='Zasedací místnost', max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('is_usable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=8)),
                ('step', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['grade'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=32)),
                ('title_before_name', models.CharField(blank=True, max_length=20, null=True)),
                ('title_after_name', models.CharField(blank=True, max_length=20, null=True)),
                ('personal_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Osobní číslo')),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=40)),
                ('nationality', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=100, validators=[django.core.validators.EmailValidator()])),
                ('start_date_of_employment', models.DateField()),
                ('contract_from', models.DateField(default=None)),
                ('contract_until', models.DateField(default=None)),
                ('initial_creditable_work_experience_years', models.PositiveIntegerField(default=0)),
                ('initial_creditable_work_experience_months', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], default=0)),
                ('initial_creditable_work_experience_days', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30')], default=0)),
                ('education_level', models.CharField(choices=[('Střední vzdělání s maturitou', 'Secondary Education'), ('Vysokoškolské vzdělání bakalářské', 'Bachelor University Degree'), ('Magisterské vysokoškolské vzdělání', 'Master University Degree')], default='Střední vzdělání s maturitou', max_length=50)),
                ('type_of_employment', models.CharField(choices=[('Hlavní pracovní poměr', 'Main Employment Relationship'), ('Dohoda o pracovní činnosti', 'Work Agreement'), ('Dohoda o provedení práce', 'Performance Work Agreement'), ('Částečný pracovní úvazek', 'Part Time Job')], default='Hlavní pracovní poměr', max_length=50)),
                ('job_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_job_position', to='viewer.jobposition')),
            ],
            options={
                'ordering': ['surname', 'name'],
            },
        ),
    ]
