# Generated by Django 5.1.7 on 2025-04-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='highway_ticket_validity',
            field=models.DateField(blank=True, null=True),
        ),
    ]
