# Generated by Django 5.1.7 on 2025-03-22 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('contract_until', models.DateField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InternalDirectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('effective_date', models.DateField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonalCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('valid_until', models.DateField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('initial_date', models.DateField()),
            ],
            options={
                'ordering': ['grade'],
            },
        ),
        migrations.AlterModelOptions(
            name='jobposition',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=32)),
                ('title_before_name', models.CharField(blank=True, max_length=20, null=True)),
                ('title_after_name', models.CharField(blank=True, max_length=20, null=True)),
                ('personal_number', models.IntegerField(blank=True, unique=True)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=40)),
                ('nationality', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('date_of_employment', models.DateField()),
                ('creditable_work_experience', models.IntegerField(default=0, help_text='Délka praxe v měsících')),
                ('education_level', models.CharField(max_length=20)),
                ('type_of_employment', models.CharField(max_length=20)),
                ('job_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_job_position', to='viewer.jobposition')),
            ],
            options={
                'ordering': ['surname', 'name'],
            },
        ),
    ]
