# Generated by Django 5.1.7 on 2025-04-11 12:19

import django.core.validators
import django.db.models.deletion
import viewer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_alter_cars_highway_ticket_validity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementWorker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=32)),
                ('title_before_name', models.CharField(blank=True, max_length=20, null=True)),
                ('title_after_name', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=40)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=100, null=True, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, validators=[viewer.models.validate_phone_number])),
                ('type_of_agreement', models.CharField(choices=[('Dohoda o pracovní činnosti', 'Work Agreement'), ('Dohoda o provedení práce', 'Performance Work Agreement')], default='Dohoda o provedení práce', max_length=32)),
                ('contract_from', models.DateField()),
                ('contract_until', models.DateField()),
                ('hourly_wage', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='viewer.employee')),
            ],
            options={
                'verbose_name': 'Pracovník s dohodou',
                'verbose_name_plural': 'Pracovníci s dohodami',
            },
        ),
    ]
