# Generated by Django 5.1.7 on 2025-03-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_contract_internaldirectives_personalcompetence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=15)),
                ('technical_inspection_date', models.DateField()),
                ('highway_ticket_validity', models.DateField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RealEstates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_until',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='creditable_work_experience',
        ),
        migrations.RemoveField(
            model_name='salarygrade',
            name='initial_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_from',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_until',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='salarygrade',
            name='step',
            field=models.IntegerField(default=1),
        ),
    ]
