# Generated by Django 5.1.7 on 2025-04-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_internaldirectives_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internaldirectives',
            name='type',
        ),
    ]
