# Generated by Django 5.1.7 on 2025-03-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_cars_realestates_remove_contract_contract_until_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='date_of_employment',
            new_name='start_date_of_employment',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='initial_creditable_work_experience',
        ),
        migrations.AddField(
            model_name='employee',
            name='initial_creditable_work_experience_days',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='initial_creditable_work_experience_months',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='initial_creditable_work_experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
