# Generated by Django 5.1.7 on 2025-03-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_total_creditable_work_experience_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='is_usable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realestates',
            name='is_usable',
            field=models.BooleanField(default=False),
        ),
    ]
