# Generated by Django 5.1.7 on 2025-04-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('viewer', '0005_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='job_positions', to='auth.permission'),
        ),
    ]
