# Generated by Django 5.1.7 on 2025-03-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_cars_is_usable_realestates_is_usable'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cars',
            name='type',
            field=models.CharField(choices=[('Osobní', 'Personal'), ('Nákladní', 'Lorry')], default='Osobní', max_length=50),
        ),
    ]
