# Generated by Django 5.1.7 on 2025-03-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_employee_email_alter_cars_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='type',
            field=models.CharField(choices=[('Osobní vozidlo', 'Passenger Vehicle'), ('Nákladní vozidlo', 'Truck')], default='Osobní vozidlo', max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(choices=[('Hlavní pracovní poměr', 'Main Employment Relationship'), ('Dohoda o pracovní činnosti', 'Work Agreement'), ('Dohoda o provedení práce', 'Performance Work Agreement'), ('Částečný pracovní úvazek', 'Part Time Job')], default='Hlavní pracovní poměr', max_length=32),
        ),
        migrations.AlterField(
            model_name='realestates',
            name='type',
            field=models.CharField(choices=[('Budova', 'Building'), ('Nájemní byt', 'Rental Apartment'), ('Společenská místnost', 'Social Hall'), ('Zasedací místnost', 'Conference Room')], default='Zasedací místnost', max_length=50),
        ),
        migrations.AlterField(
            model_name='salarygrade',
            name='grade',
            field=models.IntegerField(default=8),
        ),
    ]
