# Generated by Django 5.1.7 on 2025-03-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_alter_cars_type_alter_contract_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='fuel_type',
            field=models.CharField(choices=[('Nafta', 'Diesel'), ('Benzín', 'Gasoline'), ('Elektrický pohon', 'Electric'), ('LPG', 'Lpg')], default='Elektrický pohon', max_length=20),
        ),
    ]
