# Generated by Django 5.1.7 on 2025-03-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_cars_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='education_level',
            field=models.CharField(choices=[('Střední vzdělání s maturitou', 'Secondary Education'), ('Vysokoškolské vzdělání bakalářské', 'Bachelor University Degree'), ('Magisterské vysokoškolské vzdělání', 'Master University Degree')], default='Střední vzdělání s maturitou', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type_of_employment',
            field=models.CharField(choices=[('Hlavní pracovní poměr', 'Main Employment Relationship'), ('Dohoda o pracovní činnosti', 'Work Agreement'), ('Dohoda o provedení práce', 'Performance Work Agreement'), ('Částečný pracovní úvazek', 'Part Time Job')], default='Hlavní pracovní poměr', max_length=50),
        ),
    ]
