# Generated by Django 5.1.7 on 2025-03-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_alter_employee_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='grade',
            field=models.IntegerField(default=8),
        ),
    ]
