# Generated by Django 5.1.7 on 2025-04-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_alter_employee_email_alter_employee_personal_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\kamil\\python_final_project\\KamilAdmin\\employee_photos'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='personal_competencies',
            field=models.ManyToManyField(blank=True, to='viewer.personalcompetence'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type_of_employment',
            field=models.CharField(choices=[('Hlavní pracovní poměr', 'Main Employment Relationship'), ('Dohoda o pracovní činnosti', 'Work Agreement'), ('Dohoda o provedení práce', 'Performance Work Agreement'), ('Částečný pracovní úvazek', 'Part Time Job'), ('Uvolněný zastupitel', 'Vacant Representative')], default='Hlavní pracovní poměr', max_length=50),
        ),
    ]
