# Generated by Django 5.1.7 on 2025-04-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_alter_employee_email_alter_employee_personal_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaldirectives',
            name='type',
            field=models.CharField(choices=[('Řád', 'Regulations'), ('Směrnice', 'Directives'), ('Nařízení', 'Rules')], default='Řád', max_length=50),
        ),
    ]
