# Generated by Django 5.1.7 on 2025-04-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_internaldirectives_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalcompetence',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='jobposition',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='personal_competencies',
            field=models.ManyToManyField(blank=True, to='viewer.personalcompetence'),
        ),
        migrations.AddField(
            model_name='personalcompetence',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='personalcompetence',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
