# Generated by Django 5.1.7 on 2025-04-09 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0013_alter_employee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePersonalCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.personalcompetence')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.employee')),
            ],
            options={
                'ordering': ['competence'],
            },
        ),
    ]
