# Generated by Django 5.1.7 on 2025-04-09 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_employeepersonalcompetence'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcompetence',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='viewer.jobposition'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='personal_competencies',
            field=models.ManyToManyField(related_name='job_positions', to='viewer.personalcompetence'),
        ),
    ]
