# Generated by Django 5.1.7 on 2025-04-09 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_personalcompetence_job_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_job_position', to='viewer.jobposition'),
        ),
    ]
