# Generated by Django 5.1.7 on 2025-04-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0016_alter_employee_job_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepersonalcompetence',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
