# Generated by Django 5.1.7 on 2025-04-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0017_employeepersonalcompetence_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaldirectives',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internaldirectives',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='internal_documents/'),
        ),
    ]
