# Generated by Django 5.1.7 on 2025-04-09 15:46

import viewer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0018_internaldirectives_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[viewer.models.validate_phone_number]),
        ),
    ]
