# Generated by Django 5.1.7 on 2025-04-10 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0019_employee_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementWorker',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewer.employee')),
            ],
            options={
                'verbose_name': 'Pracovník s dohodou',
                'verbose_name_plural': 'Pracovníci s dohodami',
            },
            bases=('viewer.employee',),
        ),
    ]
